### ISSUE TITLE
Unable to deploy project to Vercel Server.

### ISSUE THREAD

**Issue by theChandrayMurmu** [vercel-labs/book-inventory#7]
![image](https://github.com/user-attachments/assets/3a86eec6-f498-44f5-b760-33005df2600b)
![image](https://github.com/user-attachments/assets/421ee45d-41d5-4ba8-889a-9eaa5cbb3064)

**Am I doing something wrong to deploy the repo the Vercel Server?** 

---
[01:49:42.525] Running build in Washington, D.C., USA (East) – iad1
[01:49:42.729] Cloning github.com/theChandrayMurmu/book-inventory (Branch: main, Commit: bfa18e7)
[01:49:43.143] Previous build cache not available
[01:49:45.934] Cloning completed: 3.216s
[01:49:46.923] Running "vercel build"
[01:49:47.904] Vercel CLI 35.2.3
[01:49:49.316] Detected `pnpm-lock.yaml` version 9 generated by pnpm 9
[01:49:49.352] Installing dependencies...
[01:49:51.056] Lockfile is up to date, resolution step is skipped
[01:49:51.170] Progress: resolved 1, reused 0, downloaded 0, added 0
[01:49:51.299] Packages: +231
[01:49:51.299] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[01:49:52.173] Progress: resolved 231, reused 0, downloaded 14, added 0
[01:49:53.173] Progress: resolved 231, reused 0, downloaded 45, added 30
[01:49:54.174] Progress: resolved 231, reused 0, downloaded 99, added 85
[01:49:55.176] Progress: resolved 231, reused 0, downloaded 111, added 99
[01:49:56.176] Progress: resolved 231, reused 0, downloaded 113, added 99
[01:49:57.177] Progress: resolved 231, reused 0, downloaded 114, added 100
[01:49:58.178] Progress: resolved 231, reused 0, downloaded 120, added 104
[01:49:59.179] Progress: resolved 231, reused 0, downloaded 127, added 111
[01:50:00.180] Progress: resolved 231, reused 0, downloaded 130, added 114
[01:50:01.180] Progress: resolved 231, reused 0, downloaded 138, added 122
[01:50:02.180] Progress: resolved 231, reused 0, downloaded 223, added 210
[01:50:02.492] Progress: resolved 231, reused 0, downloaded 231, added 231, done
[01:50:02.607] .../node_modules/bufferutil install$ node-gyp-build
[01:50:02.608] .../node_modules/utf-8-validate install$ node-gyp-build
[01:50:02.610] .../sharp@0.33.4/node_modules/sharp install$ node install/check
[01:50:02.625] .../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
[01:50:02.626] .../esbuild@0.19.12/node_modules/esbuild postinstall$ node install.js
[01:50:02.856] .../node_modules/bufferutil install: Done
[01:50:02.916] .../esbuild@0.18.20/node_modules/esbuild postinstall: Done
[01:50:02.972] .../sharp@0.33.4/node_modules/sharp install: Done
[01:50:02.979] .../esbuild@0.19.12/node_modules/esbuild postinstall: Done
[01:50:03.003] .../node_modules/utf-8-validate install: Done
[01:50:03.159] 
[01:50:03.161] dependencies:
[01:50:03.161] + @heroicons/react 2.1.5
[01:50:03.162] + @neondatabase/serverless 0.9.4
[01:50:03.162] + @next/env 14.2.5
[01:50:03.162] + @radix-ui/react-checkbox 1.1.1
[01:50:03.162] + @radix-ui/react-collapsible 1.1.0
[01:50:03.162] + @radix-ui/react-scroll-area 1.1.0
[01:50:03.162] + @radix-ui/react-slot 1.1.0
[01:50:03.162] + @tailwindcss/postcss 4.0.0-alpha.18
[01:50:03.162] + @types/node 20.14.14
[01:50:03.163] + @types/papaparse 5.3.14
[01:50:03.163] + @types/react 18.3.3
[01:50:03.163] + @types/react-dom 18.3.0
[01:50:03.163] + @vercel/postgres 0.8.0
[01:50:03.163] + autoprefixer 10.4.20
[01:50:03.163] + class-variance-authority 0.7.0
[01:50:03.163] + clsx 2.1.1
[01:50:03.163] + drizzle-kit 0.23.2
[01:50:03.163] + drizzle-orm 0.32.2
[01:50:03.163] + geist 1.3.1
[01:50:03.163] + lucide-react 0.427.0
[01:50:03.163] + next 15.0.0-canary.111
[01:50:03.164] + papaparse 5.4.1
[01:50:03.164] + postcss 8.4.41
[01:50:03.164] + prettier 3.3.3
[01:50:03.164] + react 19.0.0-rc-e948a5ac-20240807
[01:50:03.164] + react-dom 19.0.0-rc-e948a5ac-20240807
[01:50:03.164] + tailwind-merge 2.4.0
[01:50:03.164] + tailwindcss 3.4.9
[01:50:03.164] + tailwindcss-animate 1.0.7
[01:50:03.164] + typescript 5.5.4
[01:50:03.164] + use-debounce 10.0.2
[01:50:03.164] 
[01:50:03.213] Done in 13.7s
[01:50:03.247] Detected Next.js version: 15.0.0-canary.111
[01:50:03.253] Running "pnpm run build"
[01:50:03.716] 
[01:50:03.716] > @ build /vercel/path0
[01:50:03.716] > next build
[01:50:03.716] 
[01:50:04.938]  ⚠ Configuration with next.config.ts is currently an experimental feature, use with caution.
[01:50:04.957] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[01:50:04.958] This information is used to shape Next.js' roadmap and prioritize features.
[01:50:04.958] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[01:50:04.958] https://nextjs.org/telemetry
[01:50:04.958] 
[01:50:05.088]   ▲ Next.js 15.0.0-canary.111
[01:50:05.090]   - Experiments (use with caution):
[01:50:05.091]     · ppr
[01:50:05.091] 
[01:50:05.118]    Creating an optimized production build ...
[01:50:25.134]  ✓ Compiled successfully
[01:50:25.140]    Linting and checking validity of types ...
[01:50:30.485]    Collecting page data ...
[01:50:31.155] Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
[01:50:31.156]     at neon (/vercel/path0/.next/server/chunks/702.js:11:5653)
[01:50:31.156]     at 2089 (/vercel/path0/.next/server/chunks/98.js:1:16475)
[01:50:31.156]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
[01:50:31.156]     at 1100 (/vercel/path0/.next/server/chunks/98.js:1:14315)
[01:50:31.156]     at Function.t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
[01:50:31.156]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[01:50:31.156]     at async collectGenerateParams (/vercel/path0/node_modules/.pnpm/next@15.0.0-canary.111_react-dom@19.0.0-rc-e948a5ac-20240807_react@19.0.0-rc-e948a5ac-2024080_kfrjrzdxyp4mn7roak36ou66ym/node_modules/next/dist/build/utils.js:926:21)
[01:50:31.156]     at async /vercel/path0/node_modules/.pnpm/next@15.0.0-canary.111_react-dom@19.0.0-rc-e948a5ac-20240807_react@19.0.0-rc-e948a5ac-2024080_kfrjrzdxyp4mn7roak36ou66ym/node_modules/next/dist/build/utils.js:1151:17
[01:50:31.156]     at async Span.traceAsyncFn (/vercel/path0/node_modules/.pnpm/next@15.0.0-canary.111_react-dom@19.0.0-rc-e948a5ac-20240807_react@19.0.0-rc-e948a5ac-2024080_kfrjrzdxyp4mn7roak36ou66ym/node_modules/next/dist/trace/trace.js:157:20)
[01:50:31.158] 
[01:50:31.166] > Build error occurred
[01:50:31.169] Error: Failed to collect page data for /
[01:50:31.169]     at /vercel/path0/node_modules/.pnpm/next@15.0.0-canary.111_react-dom@19.0.0-rc-e948a5ac-20240807_react@19.0.0-rc-e948a5ac-2024080_kfrjrzdxyp4mn7roak36ou66ym/node_modules/next/dist/build/utils.js:1246:15
[01:50:31.169]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[01:50:31.170]   type: 'Error'
[01:50:31.170] }
[01:50:31.183]  ELIFECYCLE  Command failed with exit code 1.
[01:50:31.206] Error: Command "pnpm run build" exited with 1
[01:50:31.544]1

**Comment by esau-morais** [comment]
> Error: No database connection string was provided to neon(). Perhaps an environment variable has not been set?

have u set POSTGRES_URL to an env file?

**Comment by leerob** [comment]
^ Please let me know!

**Comment by theChandrayMurmu** [comment]
I'll check with the configuration and will let you know. @leerob @esau-morais

**Comment by leerob** [comment]
Thanks, let me know and I can reopen.
